# Generated by Django 5.0.9 on 2026-05-16 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('round_number', models.IntegerField(default=1)),
                ('turn_index', models.IntegerField(default=0)),
                ('combatants', models.JSONField(default=list)),
                ('map_data', models.JSONField(default=dict)),
                ('action_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combat', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='RollRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('dice_type', models.CharField(default='d20', max_length=10)),
                ('count', models.IntegerField(default=1)),
                ('modifier', models.IntegerField(default=0)),
                ('has_advantage', models.BooleanField(default=False)),
                ('has_disadvantage', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('public', 'Resolved Public'), ('private', 'Resolved Private'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('rolls', models.JSONField(default=list)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('is_critical_fail', models.BooleanField(default=False)),
                ('rigged', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_requests', to='api.campaign')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.character')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='api_rollreq_campaig_b9d25f_idx')],
            },
        ),
    ]
