# Generated by Django 5.2.1 on 2026-05-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_combatinstance_rollrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('consumed', 'Consumed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
