# Generated by Django 5.2.9 on 2026-09-30 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_diaryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('skill', 'Skill'), ('save', 'Save'), ('ability', 'Ability'), ('custom', 'Custom')], default='skill', max_length=10)),
                ('key', models.CharField(blank=True, default='', max_length=30)),
                ('dc', models.IntegerField(blank=True, null=True)),
                ('dc_hidden', models.BooleanField(default=False)),
                ('advantage', models.CharField(choices=[('normal', 'Normal'), ('adv', 'Advantage'), ('dis', 'Disadvantage')], default='normal', max_length=6)),
                ('target_user_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('show_on_screen', models.BooleanField(default=False)),
                ('screen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_requests', to='api.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('app', 'Rolled in app'), ('physical', 'Physical die'), ('dm', 'Entered by DM')], default='app', max_length=10)),
                ('natural', models.IntegerField(blank=True, null=True)),
                ('rolls', models.JSONField(blank=True, default=list)),
                ('modifier', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField()),
                ('rigged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.character')),
                ('check_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.checkrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='checkrequest',
            index=models.Index(fields=['campaign', 'status'], name='api_checkre_campaig_48c8c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkresponse',
            unique_together={('check_request', 'user')},
        ),
    ]
