# Generated by Django 5.2.9 on 2026-09-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_checkrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('playing', 'Playing'), ('done', 'Done')], default='draft', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('play', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='api.campaign')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['campaign', '-updated_at'], name='api_adventu_campaig_0ca0dd_idx')],
            },
        ),
    ]
