# Generated by Django 5.2.9 on 2026-10-06 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sharedcharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='accent',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cover_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cover_ver',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='campaign',
            name='dm_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='world_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorldEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('place', 'Place'), ('npc', 'NPC'), ('faction', 'Faction'), ('item', 'Item'), ('lore', 'Lore'), ('handout', 'Handout')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('summary', models.CharField(blank=True, default='', max_length=280)),
                ('body', models.TextField(blank=True, default='')),
                ('dm_notes', models.TextField(blank=True, default='')),
                ('secrets', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('hidden', 'Hidden'), ('partial', 'Partial'), ('revealed', 'Revealed')], default='hidden', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('when_label', models.CharField(blank=True, default='', max_length=60)),
                ('when_order', models.IntegerField(blank=True, null=True)),
                ('image_ver', models.CharField(blank=True, default='', max_length=16)),
                ('sort', models.IntegerField(default=0)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world', to='api.campaign')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.worldentry')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='api.worldentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='worldentry',
            index=models.Index(fields=['campaign', 'kind'], name='api_worlden_campaig_217210_idx'),
        ),
        migrations.AddIndex(
            model_name='worldentry',
            index=models.Index(fields=['campaign', 'visibility'], name='api_worlden_campaig_7018e3_idx'),
        ),
    ]
