# Generated by Django 5.2.9 on 2026-10-06 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('shiver', 'Shiver'), ('love', 'Love'), ('doubt', 'Doubt'), ('fight', 'Fight'), ('star', 'Want to return')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.worldentry')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_reactions', to='api.membership')),
            ],
            options={
                'indexes': [models.Index(fields=['membership'], name='api_worldre_members_cfb41e_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry', 'membership', 'kind'), name='uniq_world_reaction')],
            },
        ),
        migrations.CreateModel(
            name='WorldView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_at', models.DateTimeField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='api.worldentry')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_views', to='api.membership')),
            ],
            options={
                'indexes': [models.Index(fields=['membership'], name='api_worldvi_members_2b2e64_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry', 'membership'), name='uniq_world_view')],
            },
        ),
    ]
