# Generated by Django 5.2.9 on 2026-10-07 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_world_echoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('name_pt', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('campaigns', 'Campaigns'), ('storage_mb', 'Storage MB'), ('characters', 'Characters'), ('table_slots', 'Table slots per campaign')], max_length=20)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('name_pt', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('max_characters', models.PositiveIntegerField(default=3)),
                ('max_campaigns', models.PositiveIntegerField(default=1)),
                ('table_slots', models.PositiveIntegerField(default=0)),
                ('storage_mb', models.PositiveIntegerField(default=25)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addons', models.JSONField(blank=True, default=dict)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('free', 'Free'), ('admin', 'Admin'), ('payment', 'Payment')], default='admin', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'closed_at'], name='api_campaig_status_ea19e2_idx'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='api.plan'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
