/* Glossário da criação: cada termo em uma frase, para quem nunca jogou. */
const g = (ptName, enName, pt, en) => ({ name: { pt: ptName, en: enName }, desc: { pt, en } });

export const GLOSSARY = {
  class: g('Classe', 'Class', 'A "profissão" do herói: define o que ele faz bem em combate e fora dele.', 'Your hero\'s "profession": what they do well in and out of combat.'),
  subclass: g('Subclasse', 'Subclass', 'Uma especialização dentro da classe, escolhida em um nível específico.', 'A specialization within your class, chosen at a specific level.'),
  species: g('Espécie', 'Species', 'O povo do herói: humano, elfo, anão… Dá características como visão no escuro.', 'Your hero\'s people: human, elf, dwarf… Grants traits like darkvision.'),
  background: g('Antecedente', 'Background', 'O que o herói fazia antes de virar aventureiro. Dá perícias, uma ferramenta e equipamento.', 'What your hero did before adventuring. Grants skills, a tool and equipment.'),
  abilityScores: g('Atributos', 'Ability Scores', 'Seis números que medem o herói: Força, Destreza, Constituição, Inteligência, Sabedoria e Carisma.', 'Six numbers that measure your hero: Strength, Dexterity, Constitution, Intelligence, Wisdom and Charisma.'),
  modifier: g('Modificador', 'Modifier', 'O número que você soma às rolagens. Vem do atributo: 10–11 = +0, 12–13 = +1, 14–15 = +2…', 'The number you add to rolls. Comes from the score: 10–11 = +0, 12–13 = +1, 14–15 = +2…'),
  proficiency: g('Proficiência', 'Proficiency', 'Treino. Quando você é proficiente em algo, soma o Bônus de Proficiência (+2 no nível 1).', 'Training. When proficient in something you add your Proficiency Bonus (+2 at level 1).'),
  proficiencyBonus: g('Bônus de Proficiência', 'Proficiency Bonus', 'Bônus somado a tudo em que você é treinado. Começa em +2 e cresce com o nível.', 'Bonus added to everything you\'re trained in. Starts at +2 and grows with level.'),
  skill: g('Perícia', 'Skill', 'Uma área de treino, como Furtividade ou Persuasão. Quando o mestre pede um teste dela, você soma seu bônus.', 'An area of training like Stealth or Persuasion. When the DM asks for a check, you add your bonus.'),
  savingThrow: g('Teste de resistência', 'Saving Throw', 'Rolagem para resistir a algo (veneno, magia, armadilha). Cada classe é treinada em dois.', 'A roll to resist something (poison, spells, traps). Each class is trained in two.'),
  hitPoints: g('Pontos de Vida (PV)', 'Hit Points (HP)', 'A "vida" do herói. Chegando a 0, ele cai inconsciente.', 'Your hero\'s health. At 0 they fall unconscious.'),
  hitDie: g('Dado de Vida', 'Hit Die', 'Dado da classe que define seus PV (d6 a d12). Também cura nos descansos curtos.', 'Your class die that sets your HP (d6 to d12). Also heals on short rests.'),
  armorClass: g('Classe de Armadura (CA)', 'Armor Class (AC)', 'O quão difícil é te acertar: o inimigo precisa tirar isso ou mais no ataque.', 'How hard you are to hit: enemies must roll this or higher.'),
  cantrip: g('Truque', 'Cantrip', 'Magia simples que você pode lançar quantas vezes quiser.', 'A simple spell you can cast as often as you like.'),
  spellSlot: g('Espaço de magia', 'Spell Slot', 'A "energia" para lançar magias de 1º círculo ou mais. Volta no descanso longo.', 'The "fuel" to cast level 1+ spells. Comes back on a long rest.'),
  preparedSpell: g('Magia preparada', 'Prepared Spell', 'As magias que você deixou prontas para usar hoje. Pode trocar depois de um descanso longo.', 'The spells you have ready today. You can swap them after a long rest.'),
  spellbook: g('Grimório', 'Spellbook', 'O livro do mago com todas as magias que ele aprendeu; ele prepara magias a partir dele.', 'The wizard\'s book with every spell learned; they prepare spells from it.'),
  feat: g('Talento', 'Feat', 'Uma habilidade especial extra, como ficar mais atento ou aprender magia.', 'An extra special ability, like being more alert or learning magic.'),
  originFeat: g('Talento de origem', 'Origin Feat', 'Talento que vem do seu antecedente no nível 1.', 'A feat your background grants at level 1.'),
  weaponMastery: g('Maestria em Armas', 'Weapon Mastery', 'Um efeito extra ao atacar com certas armas (empurrar, derrubar, atrasar…).', 'An extra effect when attacking with certain weapons (push, topple, slow…).'),
  fightingStyle: g('Estilo de Luta', 'Fighting Style', 'Um jeito de lutar em que você é melhor, como com armas de duas mãos ou com arco.', 'A way of fighting you excel at, like two-handed weapons or archery.'),
  alignment: g('Tendência', 'Alignment', 'A bússola moral do herói (bom, mau, leal, caótico). Opcional e só um guia.', 'Your hero\'s moral compass (good, evil, lawful, chaotic). Optional, just a guide.'),
  darkvision: g('Visão no Escuro', 'Darkvision', 'Enxerga no escuro como se fosse penumbra, em tons de cinza.', 'See in darkness as if it were dim light, in shades of gray.'),
  speed: g('Deslocamento', 'Speed', 'Quantos metros o herói anda no seu turno.', 'How far your hero moves on their turn.'),
  initiative: g('Iniciativa', 'Initiative', 'Rolagem que decide a ordem dos turnos no combate.', 'The roll that decides turn order in combat.'),
  passivePerception: g('Percepção passiva', 'Passive Perception', 'O quanto o herói nota sem procurar (10 + bônus de Percepção).', 'How much your hero notices without looking (10 + Perception bonus).'),
  tool: g('Ferramenta', 'Tool', 'Kit de ofício (ladrão, ferreiro, herbalismo…). Proficiente = soma o bônus ao usá-lo.', 'A trade kit (thieves\', smith\'s, herbalism…). Proficient = add your bonus when using it.'),
  language: g('Idioma', 'Language', 'Línguas que o herói fala, lê e escreve.', 'Languages your hero speaks, reads and writes.'),
  milestone: g('Marcos', 'Milestones', 'O mestre diz quando todos sobem de nível, sem contar pontos de experiência.', 'The DM says when everyone levels up, no experience points.'),
  xp: g('XP', 'XP', 'Pontos de experiência ganhos em aventuras; ao juntar o bastante, sobe de nível.', 'Experience points earned on adventures; with enough you level up.'),
  ritual: g('Ritual', 'Ritual', 'Magia que pode ser lançada mais devagar (10 min a mais) sem gastar espaço de magia.', 'A spell you can cast slowly (10 extra minutes) without using a slot.'),
  concentration: g('Concentração', 'Concentration', 'Magia que dura enquanto você se concentra; só uma por vez, e dano pode quebrá-la.', 'A spell that lasts while you focus; only one at a time, and damage can break it.'),
};
